# Generated by Django 3.2.6 on 2021-09-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes_and_ingredients', '0001_initial'),
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes_and_ingredients.recipe'),
        ),
    ]
