# Generated by Django 3.2.6 on 2021-08-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes_and_ingredients', '0002_auto_20210823_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientExpiryDate', models.DateField()),
                ('FreezerWeight', models.FloatField()),
                ('FridgeWeight', models.FloatField()),
                ('PantryWeight', models.FloatField()),
                ('ingredientGTIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_and_ingredients.ingredient')),
            ],
        ),
    ]
