# Generated by Django 3.2.6 on 2021-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedingredientinpantry',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
