# Generated by Django 3.2.6 on 2021-08-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedingredient',
            old_name='ingredientExpiryDate',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='storedingredient',
            old_name='FreezerWeight',
            new_name='freezer_weight',
        ),
        migrations.RenameField(
            model_name='storedingredient',
            old_name='FridgeWeight',
            new_name='fridge_weight',
        ),
        migrations.RenameField(
            model_name='storedingredient',
            old_name='ingredientGTIN',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='storedingredient',
            old_name='PantryWeight',
            new_name='pantry_weight',
        ),
    ]
