# Generated by Django 3.2.6 on 2021-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedingredientinfreezer',
            name='kg',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='storedingredientinfridge',
            name='kg',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='storedingredientinpantry',
            name='kg',
            field=models.FloatField(default=1),
        ),
    ]
