# Generated by Django 3.2.6 on 2021-09-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_space', '0003_storedingredient_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedingredient',
            name='freezer_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='storedingredient',
            name='fridge_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='storedingredient',
            name='pantry_weight',
            field=models.FloatField(default=0),
        ),
    ]
