# Generated by Django 3.2.6 on 2021-09-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_space', '0004_auto_20210901_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedingredient',
            old_name='freezer_weight',
            new_name='kg_in_freezer',
        ),
        migrations.RenameField(
            model_name='storedingredient',
            old_name='fridge_weight',
            new_name='kg_in_fridge',
        ),
        migrations.RenameField(
            model_name='storedingredient',
            old_name='pantry_weight',
            new_name='kg_in_pantry',
        ),
    ]
