# Generated by Django 3.2.6 on 2021-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_space', '0006_auto_20210908_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedingredientinpantry',
            name='expiry_date',
            field=models.CharField(max_length=15),
        ),
    ]
