# Generated by Django 3.2.6 on 2021-09-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes_and_ingredients', '0012_rename_weight_used_recipeingredient_kg_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_and_ingredients.recipe')),
            ],
        ),
    ]
