# Generated by Django 3.2.6 on 2021-10-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210927_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityrecipe',
            name='likes',
        ),
    ]
