# Generated by Django 3.2.6 on 2021-08-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_feature', '0006_auto_20210823_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientGTIN', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredientName', models.CharField(max_length=100)),
                ('ingredientExpiryDate', models.DateField()),
                ('ingredientType', models.CharField(choices=[('1', 'Meat, Seafood & Deli'), ('2', 'Fruit & Veg'), ('3', 'Dairy, Eggs & Fridge'), ('4', 'Bakery'), ('5', 'Freezer'), ('6', 'Pantry')], default='Meat, Seafood & Deli', max_length=50)),
                ('ingredientWeight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Ingredients', models.ManyToManyField(to='recipes_and_ingredients.Ingredient')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_feature.customer')),
                ('tags', models.ManyToManyField(to='recipes_and_ingredients.Tags')),
            ],
        ),
    ]
