# Generated by Django 3.2.6 on 2021-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='kg_used',
            field=models.FloatField(default=1),
        ),
    ]
