# Generated by Django 3.2.6 on 2021-08-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredientExpiryDate',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredientWeight',
        ),
    ]
