# Generated by Django 3.2.6 on 2021-08-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0002_auto_20210823_1851'),
        ('recipes_and_ingredients', '0005_rename_tags_tag'),
    ]

    operations = [
    ]
