# Generated by Django 3.2.6 on 2021-08-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0006_merge_0002_auto_20210823_1851_0005_rename_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='needed_ingredients',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightUsedInRecipe', models.FloatField()),
                ('ingredientGTIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_and_ingredients.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(to='recipes_and_ingredients.RecipeIngredient'),
        ),
    ]
