# Generated by Django 3.2.6 on 2021-08-31 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0007_auto_20210831_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
