# Generated by Django 3.2.6 on 2021-08-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0008_recipe_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientGTIN',
            new_name='ingredient_gtin',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientName',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientType',
            new_name='ingredient_type',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredientGTIN',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='weightUsedInRecipe',
            new_name='weight_used',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='name',
        ),
    ]
