# Generated by Django 3.2.6 on 2021-09-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0011_remove_ingredient_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='weight_used',
            new_name='kg_used',
        ),
    ]
