# Generated by Django 3.2.6 on 2021-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0012_rename_weight_used_recipeingredient_kg_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='photo',
            field=models.ImageField(default='ingredients/test_photo.PNG', upload_to='ingredients'),
        ),
    ]
