# Generated by Django 3.2.6 on 2021-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0013_ingredient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='ingredients/test_photo.PNG', upload_to='ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='Masak air', max_length=1000),
            preserve_default=False,
        ),
    ]
