# Generated by Django 3.2.6 on 2021-09-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0010_alter_customer_bio'),
        ('recipes_and_ingredients', '0014_auto_20210915_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='customers_who_saved',
            field=models.ManyToManyField(related_name='customers_who_saved', to='profile_feature.Customer'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='profile_feature.customer'),
        ),
    ]
