# Generated by Django 3.2.6 on 2021-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_ingredients', '0015_auto_20210915_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='customers_who_saved',
            new_name='customers_who_save',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='recipes/test_photo.PNG', upload_to='recipes'),
        ),
    ]
