# Generated by Django 3.2.6 on 2021-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='profilePic/GDR.PNG', upload_to='profilePic'),
        ),
    ]
