# Generated by Django 3.2.6 on 2021-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/test_photo.png', null=True, upload_to='profile_photos'),
        ),
    ]
