# Generated by Django 3.2.6 on 2021-08-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0002_auto_20210816_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
