# Generated by Django 3.2.6 on 2021-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0003_alter_customer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='profilePic/GDR.PNG', null=True, upload_to='profilePic'),
        ),
    ]
