# Generated by Django 3.2.6 on 2021-08-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0005_auto_20210823_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
