# Generated by Django 3.2.6 on 2021-08-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0006_auto_20210823_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photo/GDR.PNG', null=True, upload_to='profile_photo'),
        ),
    ]
