# Generated by Django 3.2.6 on 2021-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0007_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photo/test_photo.PNG', null=True, upload_to='profile_photo'),
        ),
    ]
