# Generated by Django 3.2.6 on 2021-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_feature', '0009_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
